services:
  db:
    image: postgres:17
    container_name: lacrei-postgres

    environment:
      POSTGRES_DB: lacrei
      POSTGRES_USER: lacrei
      POSTGRES_PASSWORD: lacrei123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: