# Generated by Django 6.1 on 2026-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('profissional', 'data'), name='unique_professional_appointment_datetime'),
        ),
    ]
